### PR TITLE
Preliminary EMI integration

### PR DESCRIPTION
**Pull request by unilock**
This PR integrates NEEPMeat with [EMI](https://github.com/emilyploszaj/emi), yet another item and recipe viewer.

TODO:
- [x] Manufacture recipes
- [x] Compacting and Heart Extraction recipe IDs?
- [x] The Enlightening recipe's drawable ([link](https://github.com/unilock/NeepMeat/blob/1bf3437bda85a28fc5dad943e9d53e5f7c7cee41/src/main/java/com/neep/neepmeat/compat/emi/recipe/EnlighteningEmiRecipe.java#L85))

### CODE REVIEW

**Comment by MeatWheeze** [comment]
Thanks very much for the contribution! :)
Surgery and its corresponding transforming tool recipe are no longer needed since they've been replaced with Manufacture.
In EnlighteningCategory, the renderer thing wasn't actually doing anything. I've since changed it to a helpful textured widget.

**Comment by unilock** [comment]
Upon finally testing an instance with REI for the first time, I noticed that, in comparison to EMI, every recipe looks... a pixel or so off?

Left: EMI  
Right: REI
Screenshot 2023-12-21 at 6 13 37 PM Screenshot 2023-12-21 at 6 16 18 PM

I'm worried about messing with the `x` / `y` parameters *too* much, since I don't want to increase the slight differences in implementation between the EMI and REI plugins, but...

**Comment by unilock** [comment]
Everything should now be implemented (as) correctly (as possible). I guess that just leaves the previously mentioned alignment issue, in terms of immediate matters. @MeatWheeze, let me know what you think?

**Comment by MeatWheeze** [comment]
It doesn't seem to be much of an issue as long as all of the elements stay within the boundary (although my philosophy with REI integration has been 'even a display with horrific alignment is better than nothing').
I think minor differences are unavoidable given that the two recipe viewers seem to have apply different padding on the widgets:
image
image

**Comment by unilock** [comment]
Well, if you think it's alright, then I suppose this is ready to merge :)

**Pull request merged**
